package com.example.nodemanagement.entity;

import jakarta.persistence.*;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Pattern;
import lombok.Data;


/**
 * Node entity
 *
 * This entity maps to the "nodes" table in the database.
 * Each node is associated with a parent node through a many-to-one relationship.
 *
 * Note : Instead of using the @Pattern annotation for validation,
 * we could use a custom validator with @Constraint annotation to enforce more complex validation logic.
 *
 */


@Entity
@Data
@Table(name = "nodes")
public class Node {

    // Surrogate key : Generated by the database

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;


    // Natural key : A unique identifier for the node provided by business logic

    @NotBlank
    @Pattern(regexp = "^[a-zA-Z0-9_]*$", message = "Special characters are not allowed in nodeId")
    @Column(name = "node_id", nullable = false, unique = true)
    private String nodeId;

    @NotBlank
    @Pattern(regexp = "^[a-zA-Z0-9_ ]*$", message = "Special characters are not allowed in nodeName")
    @Column(name = "node_name", nullable = false)
    private String nodeName;

    private String description;

    private String memo;

    @Enumerated(EnumType.STRING)
    private ENodeType nodeType;

    @ManyToOne
    @JoinColumn(name = "parent_node_group_id", referencedColumnName = "parent_node_group_id")
    private ParentNode parentNode;

}
