package com.example.nodemanagement.entity;


import jakarta.persistence.*;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Pattern;
import lombok.Data;

/**
 * ParentNode entity
 *
 * This entity maps to the "parent_nodes" table in the database.
 * Each parent node can have multiple nodes associated with it.
 *
 * Note : Instead of using Enum fields, we could use a separate table to store the parent node group names
 *
 */

@Entity
@Data
@Table(name="parent_nodes")
public class ParentNode {

    // Surrogate key : Generated by the database

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    // Natural key : A unique identifier for the parent node provided by business logic

    @NotBlank
    @Pattern(regexp = "^[a-zA-Z0-9_]*$", message = "Special characters are not allowed in parentNodeGroupId")
    @Column(name = "parent_node_group_id", nullable = false, unique = true)
    private String parentNodeGroupId;

    @NotBlank
    @Pattern(regexp = "^[a-zA-Z0-9_ ]*$", message = "Special characters are not allowed in parentNodeName")
    private String parentNodeName;

    @Enumerated(EnumType.STRING)
    private EParentNodeGroupName parentNodeGroupName;

}
